### ISSUE TITLE
Run through shellcheck.net

### ISSUE THREAD

**Issue by mholt** [caddyserver/getcaddy.com#6]
Somebody pointed me to [shellcheck.net](https://www.shellcheck.net/) and I found it quite useful:

The current released version of the getcaddy.com script has these outputs:

```
 
Line 56:
        [[ ((EUID)) && -z "$ANDROID_ROOT" ]] && sudo_cmd="sudo"
             ^-- SC2078: This expression is constant. Did you forget a $ somewhere?
 
Line 94:
                IFS='.' read OSX_MAJOR OSX_MINOR OSX_PATCH <<<"$OSX_VER"
                ^-- SC2162: read without -r will mangle backslashes.
                                                 ^-- SC2034: OSX_PATCH appears unused. Verify it or export it.
 
Line 132:
                caddy_backup="$caddy_path_$caddy_cur_ver"
                              ^-- SC2154: caddy_path_ is referenced but not assigned (did you mean 'caddy_path'?).
 
Line 144:
        caddy_file="caddy_$caddy_os_$caddy_arch$caddy_arm_custom$caddy_dl_ext"
                          ^-- SC2154: caddy_os_ is referenced but not assigned (did you mean 'caddy_os'?).
                                               ^-- SC2154: caddy_arm_custom is referenced but not assigned.
```

/cc @pepa65 - I can probably resolve these but I wanted to check with you first (or see if you just wanted to tackle it instead?) - what do you think?

**Comment by pepa65** [comment]
Line 56 didn't show up for me on the online checker, you might have used an older version (because it is wrong). Line 94: there are no backslashes (to escape characters or otherwise) in $OSX_VER, and indeed, OSX_PATCH isn't used, so I put the 'ignore' placeholder instead.

The rest of the lines exonerate your curly-brackets care: because _ is a legal filename character, it must be separated from literal use... Again, bad on me. Pull request ready.

**Comment by mholt** [comment]
Thanks! And yeah, you're right, I used the one on getcaddy.com which was updated when 0.9.4 was released, I'll update it again but it is already slightly out of date.

You're right about the no backslashes, I think we can ignore that warning. Cheers for the fix!

**Comment by mholt** [comment]
@pepa65 Was just looking this over again -- do you think we should move this at the top:

```bash
if [[ $- == *i* ]]; then
	echo "Pipe into bash or run as script (after chmod +x $0)"
	echo "Don't source, your shell will disappear on any error!"
	return
fi
```

into the top of the `install_caddy` function? That way, we can be sure this code won't run unless it downloads completely.

**Comment by pepa65** [comment]
The idea of the function is, that because of starting the function, all commands in it won't get run until the function is fully defined.

The "check for sourcing" only gets activated when the script is not run but sourced, this is the best place, you don't need or want it to be part of the install_caddy function I think. And it can only be sourced once it's downloaded.

**Comment by pepa65** [comment]
On second consideration, this section is only needed because we use 'exit' in the function instead of 'return'. If we used return instead of exit, it could be sourced as well, extending the scope where the code could be run correctly. It could then be piped, or run (after chmod +x) or sourced.

That would be both a simplification and an improvement, deleting the whole clause and replace every exit with a return. Your call of course; it would want some testing to make sure it works as expected.

**Comment by mholt** [comment]
Hmm, good idea -- let's try it with return instead of exit. I've got a VM I can test it in.

**Comment by pepa65** [comment]
Go ahead..!
